language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-28.0.0
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
   - ./gradlew build connectedCheck
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"